openapi: 3.0.4
info:
  title: DogeHoot API 1.0
  description: |-
    API de DogeHoot - Plataforma educativa de cuestionarios interactivos. Puedes encontrar la aplicación en [DogeHoot](https://dmailproject.pythonanywhere.com/).
    
    Esta API permite gestionar usuarios, cuestionarios, preguntas, partidas y más funcionalidades de la plataforma educativa.

    Links útiles:
    - [Repositorio del proyecto](https://github.com/Nicols7A4/DogeHoot)
  termsOfService: https://swagger.io/terms/
  contact:
    email: 73073168@usat.pe
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12
externalDocs:
  description: Más información sobre Swagger
  url: https://swagger.io
servers:
  - url: https://dmailproject.pythonanywhere.com/
tags:
  - name: usuarios
    description: Operaciones sobre usuarios de la plataforma DogeHoot
    externalDocs:
      description: Más información
      url: https://swagger.io
  - name: cuestionarios
    description: Gestión de cuestionarios educativos
    externalDocs:
      description: Más información
      url: https://swagger.io
  - name: partidas
    description: Sesiones de juego y gestión de partidas
paths:
  /api_obtener_usuarios:
    get:
      tags:
        - usuarios
      summary: Obtener todos los usuarios
      description: Retorna la lista completa de usuarios registrados en la plataforma
      operationId: obtenerUsuarios
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  usuarios:
                    type: array
                    items:
                      $ref: '#/components/schemas/Usuario'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Error inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - jwt_auth: []
  /api_obtener_usuario_por_id/{id_usuario}:
    get:
      tags:
        - usuarios
      summary: Obtener usuario por ID
      description: Retorna la información de un usuario específico según su ID
      operationId: obtenerUsuarioPorId
      parameters:
        - name: id_usuario
          in: path
          description: ID del usuario a obtener
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  usuario:
                    $ref: '#/components/schemas/Usuario'
        '404':
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Error inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - jwt_auth: []
  /api_registrar_usuario:
    post:
      tags:
        - usuarios
      summary: Registrar un nuevo usuario
      description: Crea un nuevo usuario en la plataforma con los datos proporcionados
      operationId: registrarUsuario
      requestBody:
        description: Datos del usuario a registrar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioRegistro'
      responses:
        '201':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  mensaje:
                    type: string
                    example: Usuario registrado exitosamente
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Faltan datos requeridos
        '409':
          description: Conflicto - Usuario ya existe
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: El correo ya está registrado
        default:
          description: Error inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - jwt_auth: []
  /api_actualizar_usuario:
    put:
      tags:
        - usuarios
      summary: Actualizar información de usuario
      description: Actualiza los datos de un usuario existente
      operationId: actualizarUsuario
      requestBody:
        description: Datos del usuario a actualizar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioActualizacion'
      responses:
        '200':
          description: Usuario actualizado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  usuario:
                    $ref: '#/components/schemas/Usuario'
        '400':
          description: Datos inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflicto - Correo o nombre de usuario ya existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Error inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - jwt_auth: []
  /api_eliminar_usuario:
    post:
      tags:
        - usuarios
      summary: Eliminar (desactivar) usuario
      description: Desactiva un usuario de la plataforma (no se elimina físicamente)
      operationId: eliminarUsuario
      requestBody:
        description: ID del usuario a eliminar
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id_usuario
              properties:
                id_usuario:
                  type: integer
                  format: int32
                  example: 5
      responses:
        '200':
          description: Usuario desactivado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  id_usuario:
                    type: integer
                    example: 5
                  vigente:
                    type: boolean
                    example: false
        '404':
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Usuario no encontrado
        '500':
          description: Error al desactivar usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: No se pudo desactivar el usuario
        default:
          description: Error inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - jwt_auth: []
    delete:
      tags:
        - usuarios
      summary: Eliminar (desactivar) usuario
      description: Desactiva un usuario de la plataforma (no se elimina físicamente)
      operationId: eliminarUsuarioDelete
      requestBody:
        description: ID del usuario a eliminar
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id_usuario
              properties:
                id_usuario:
                  type: integer
                  format: int32
                  example: 5
      responses:
        '200':
          description: Usuario desactivado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  id_usuario:
                    type: integer
                    example: 5
                  vigente:
                    type: boolean
                    example: false
        '404':
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Usuario no encontrado
        '500':
          description: Error al desactivar usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: No se pudo desactivar el usuario
        default:
          description: Error inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - jwt_auth: []
components:
  schemas:
    Usuario:
      type: object
      properties:
        id_usuario:
          type: integer
          format: int32
          example: 1
        nombre_completo:
          type: string
          example: Juan Pérez García
        correo:
          type: string
          format: email
          example: juan.perez@usat.edu.pe
        nombre_usuario:
          type: string
          example: juanperez
        foto:
          type: string
          nullable: true
          example: /static/img/usuario/user123.jpg
        tipo:
          type: string
          enum: [E, P, A]
          description: Tipo de usuario - E (Estudiante), P (Profesor), A (Administrador)
          example: E
        puntos:
          type: integer
          format: int32
          nullable: true
          example: 1500
        monedas:
          type: integer
          format: int32
          nullable: true
          example: 250
        vigente:
          type: boolean
          example: true
        verificado:
          type: boolean
          example: true
        id_skin_activa:
          type: integer
          format: int32
          nullable: true
          example: 3
    UsuarioRegistro:
      type: object
      required:
        - nombre_completo
        - nombre_usuario
        - correo
        - contrasena
      properties:
        nombre_completo:
          type: string
          example: María López Torres
          minLength: 1
        nombre_usuario:
          type: string
          example: marialopez
          minLength: 1
          maxLength: 18
        correo:
          type: string
          format: email
          example: maria.lopez@usat.edu.pe
          description: Debe ser un correo @usat.edu.pe o @usat.pe
        contrasena:
          type: string
          format: password
          example: Password123!
          minLength: 8
          description: Debe contener al menos 8 caracteres, mayúsculas, minúsculas, números y símbolos especiales
        tipo:
          type: string
          enum: [E, P]
          example: E
          description: Tipo de usuario - E (Estudiante), P (Profesor). Se determina automáticamente por el dominio del correo
    UsuarioActualizacion:
      type: object
      required:
        - id_usuario
      properties:
        id_usuario:
          type: integer
          format: int32
          example: 5
        nombre_completo:
          type: string
          example: Juan Pérez García
        nombre_usuario:
          type: string
          example: juanperez
          maxLength: 18
        correo:
          type: string
          format: email
          example: juan.perez@usat.edu.pe
        tipo:
          type: string
          enum: [E, P, A]
          example: E
        puntos:
          type: integer
          format: int32
          minimum: 0
          example: 2000
        monedas:
          type: integer
          format: int32
          minimum: 0
          example: 300
        vigente:
          type: boolean
          example: true
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  securitySchemes:
    jwt_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Autenticación mediante JSON Web Token (JWT). Incluir el token en el header Authorization con el formato "Bearer {token}"